In [2]:
import numpy as np 


In [6]:
arr=np.array([[1,2,3],[4,5,6]],np.int32)
print (arr)
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [12]:
arr.shape

(2, 3)

In [13]:
arr.dtype


dtype('int32')

In [15]:
arr[1,2]

6

In [19]:
arr[:,2]

array([3, 6])

In [26]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
b= np.ones((2,3,4),dtype=np.int16)
b

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [35]:
c=np.empty((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
 d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [41]:
d= np.arange(0,2,0.1)
d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])