In [1]:
import numpy as np 


In [2]:
arr=np.array([[1,2,3],[4,5,6]],np.int32)
print (arr)
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [3]:
arr.shape

(2, 3)

In [4]:
arr.dtype


dtype('int32')

In [5]:
arr[1,2]

6

In [6]:
arr[:,2]

array([3, 6])

In [7]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b= np.ones((2,3,4),dtype=np.int16)
b

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
c=np.empty((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
 d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [11]:
np.arange(0,2,0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [12]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0],
              [3,4]] )
A*B#elementwse product


array([[2, 0],
       [0, 4]])

In [16]:
A@B#matrx product

array([[5, 4],
       [3, 4]])

In [17]:
A.dot(B)#matrx product


array([[5, 4],
       [3, 4]])

In [24]:
f=np.arange(24).reshape((3,8))
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [27]:
f.sum(axis=0)

array([24, 27, 30, 33, 36, 39, 42, 45])

In [32]:
 f.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
a=np.random.random((2,3))
b=np.random.random((2,3))

In [40]:
np.vstack((a,b))

array([[0.55731913, 0.84013088, 0.64179755],
       [0.29038889, 0.12155719, 0.46235764],
       [0.25020253, 0.15793749, 0.30403649],
       [0.27941228, 0.42528243, 0.12090048]])

In [42]:
np.hstack((a,b))

array([[0.55731913, 0.84013088, 0.64179755, 0.25020253, 0.15793749,
        0.30403649],
       [0.29038889, 0.12155719, 0.46235764, 0.27941228, 0.42528243,
        0.12090048]])

In [44]:
np.hsplit(a,3)

[array([[0.55731913],
        [0.29038889]]), array([[0.84013088],
        [0.12155719]]), array([[0.64179755],
        [0.46235764]])]